; jcl212 - PlatformIO configuration for Lab 2
[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200  ; jcl212 - must match Serial.begin(BAUD_RATE) in main.cpp
